### ISSUE TITLE
Tests fails since 2015-12-31

### ISSUE THREAD

**Issue by eserte** [ivanwills/git-workflow-tools#8]
See http://matrix.cpantesters.org/?dist=App-Git-Workflow%200.99;reports=1#sl=7,1 for a pass/fail overview.

**Comment by ivanwills** [comment]
Have release new version (actually v1.0) which should fix this issue for future years. Will wait for cpan testers to confirm before closing.

**Comment by ivanwills** [comment]
CPAN testers is now looking (mostly) good, this issue looks resolved
